# Generated by Django 4.0.5 on 2022-07-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTypes1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.BinaryField(max_length=5)),
                ('file', models.FileField(blank=True, upload_to='uploads')),
            ],
        ),
    ]
