# Generated by Django 4.0.5 on 2022-07-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index1', '0002_fieldtypes1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('image', models.ImageField(upload_to='upload_image')),
                ('file', models.FileField(blank=True, upload_to='uploads')),
            ],
        ),
    ]
