# Generated by Django 4.0.5 on 2022-07-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index1', '0003_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTypes2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=4, max_digits=5)),
                ('age', models.PositiveIntegerField()),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(default=True, upload_to='uploads')),
                ('url', models.URLField()),
                ('text', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
