# Generated by Django 4.0.5 on 2022-07-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('fr', 'Freshman'), ('so', 'Sophomore'), ('jr', 'Junior'), ('sr', 'Senior'), ('gr', 'Graduate')], default='Freshman', max_length=10)),
            ],
        ),
    ]
