# Generated by Django 4.0.5 on 2022-07-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('fr', 'Freshman'), ('so', 'Sophomore'), ('ju', 'Junior'), ('se', 'Senior'), ('gu', 'Graduate')], default='fr', max_length=10)),
            ],
        ),
    ]
