# Generated by Django 4.0.5 on 2022-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_student1'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name1', max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(default='you101@gmail.com', max_length=100)),
            ],
        ),
    ]
