# Generated by Django 4.0.5 on 2022-07-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_fieldoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOption1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True)),
            ],
        ),
    ]
