# Generated by Django 4.0.5 on 2022-07-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_fieldoption1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('number1', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name1', max_length=100)),
            ],
        ),
    ]
