# Generated by Django 4.0.5 on 2022-07-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fieldoption2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(editable=False, max_length=100)),
                ('age', models.IntegerField(db_column='age2', default='1')),
            ],
        ),
    ]
