# Generated by Django 4.0.5 on 2022-07-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_fieldoption2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOption3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message4', models.CharField(help_text='this field case sensitive', max_length=100)),
            ],
        ),
    ]
