# Generated by Django 4.0.5 on 2022-07-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_fieldoption3'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOption4',
            fields=[
                ('user_1', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('number_2', models.IntegerField()),
            ],
        ),
    ]
