# Generated by Django 4.0.5 on 2022-07-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_fieldoption4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user2', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(unique=True)),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
    ]
