# Generated by Django 4.0.5 on 2022-07-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_field1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user3', models.CharField(default='name', help_text='only for name', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField(db_index=True)),
            ],
        ),
    ]
