# Generated by Django 4.0.5 on 2022-07-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_field2'),
    ]

    operations = [
        migrations.AddField(
            model_name='field2',
            name='user_name',
            field=models.CharField(db_index=True, default='abc', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field2',
            name='number',
            field=models.IntegerField(),
        ),
    ]
