# Generated by Django 4.0.5 on 2022-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_field2_user_name_alter_field2_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user4', models.CharField(max_length=50)),
                ('age4', models.IntegerField()),
            ],
        ),
    ]
